---
title: "House Price Regression"
author: "Suzanne"
date: "25 June 2017"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(data.table)
library(ggplot2)
library(tidyverse)
library(ggcorrplot)
library(caret)

if (Sys.info()["nodename"]=="P37") {
  WorkDir <- "D:/kaggle/"
  FuncDir <- "C:/Users/Suzanne/OneDrive - Suzanne Fox/R/myFunctions/"
} else {
  WorkDir <- "C:/Users/suzan/Documents/Kaggle/"
}

File.train <- "train.csv"
data.train.orig <- fread(paste0(WorkDir, File.train))
source(paste0(FuncDir,"R_FUNCTIONS.R"))

# EDA =====================================================
# understand the basic shape of the data
data.train <- data.train.orig
data.shape <- myShape(data.train, TRUE)

write.csv(data.shape, paste0(WorkDir,"shape.csv"), row.names=FALSE)

# look at missing values
data.missing <- data.shape %>%
  filter(MISSING_COUNT > 0) %>%
  arrange(DATA_TYPE, desc(MISSING_PCENT))

# drop some variables 
dropvars <- c("PoolQC","MiscFeature","Alley","Fence",
              "FireplaceQu","LotFrontage","GarageYrBlt")
data.train <- data.train.orig %>%
  select(-one_of(dropvars))

data.shape <- myShape(data.train)

# look at near zero variance
data.zerovar <- data.shape %>%
  filter(CARET_NRZEROVAR > 0) 

# drop near zero variance data
dropvars <- data.zerovar$COLUMN_NAME
data.train <- data.train %>%
  select(-one_of(dropvars))

data.shape <- myShape(data.train)

rm(data.missing, data.zerovar)

# fill NA values with central statistics
data.train = DMwR::centralImputation(data.train)

```

## R Markdown

```{r plots, echo=FALSE, fig.width = 6, fig.height = 3}
# VIZ ======================================================

data.shape <- myShape(data.train)

# set the factors so ggplot2 doesn't order alphabetically
data.shape$COLUMN_NAME <- factor(data.shape$COLUMN_NAME, 
                                 levels=unique(data.shape$COLUMN_NAME))

# visualise the missing and unique levels
ggplot(data.shape, aes(COLUMN_NAME, MISSING_PCENT)) + 
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("Missing Value percent")

ggplot(data.shape, aes(COLUMN_NAME, UNIQUE_PCENT)) + 
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("Unique Value percent")

# box plots for character variables ========================

variables.char <- as.vector(data.shape$COLUMN_NAME[data.shape$DATA_TYPE=="character"])

for (i in seq_along(variables.char)) {
  x <- c(variables.char[i], "SalePrice")
  
  print(paste(i, "plotting", x[1]))
  
  xplot <- data.train %>%
    select(one_of(x[1]), SalePrice) %>%
    ggplot(aes_string(x[1], "SalePrice")) +
    geom_boxplot() +
    geom_jitter(alpha = 0.1, colour="coral") +
    theme(axis.text.x = element_text(angle = 90, hjust =1)) +
    xlab(x[1])

  plot(xplot)
}

# scatter charts for numerics ==============================

variables.nums <- as.vector(data.shape$COLUMN_NAME[data.shape$DATA_TYPE=="integer"])
variables.nums <- setdiff(variables.nums,c("Id"))

# ggplot(dat, aes(x=xvar, y=yvar)) +
#     geom_point(shape=1) +    # Use hollow circles
#     geom_smooth()            # Add a loess smoothed fit curve with confidence region

for (i in seq_along(variables.nums)) {
  x <- c(variables.nums[i], "SalePrice")
  
  print(paste(i, "plotting", x[1]))
  
  xplot <- data.train %>%
    select(one_of(x[1]), SalePrice) %>%
    ggplot(aes_string(x[1], "SalePrice")) +
    geom_point(shape=1) +
    geom_smooth() +
    ggtitle(x[1])

  plot(xplot)
}

```

<!-- ## Including Plots -->

<!-- You can also embed plots, for example: -->

<!-- ```{r pressure, echo=FALSE} -->
<!-- plot(pressure) -->
<!-- ``` -->

<!-- Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot. -->
